name: Build Stratos EXE

on: [push] # Собирать каждый раз, когда вы обновляете код

jobs:
  build:
    runs-on: windows-latest # Запускаем на облачной Windows

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Build with PyInstaller
      run: |
        pyinstaller --noconfirm --onefile --windowed --add-data "drivers;drivers" main.py

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: Stratos_Analyzer_EXE
        path: dist/main.exe
